routes/web.php
Route::get('notificationRead/{id}', 'UserController@notificationRead');
Route::get('notifyUsers/{keyword}/{text}/{link}' , 'UserController@notifyUsers');

Route::get('invisible_registration', 'InvisibleController@index');
Route::get('invisible_login', 'InvisibleController@login')->name('invisible_login');
Route::post('addInvisible' , 'InvisibleController@addInvisible');
Route::post('loginInvisible' , 'InvisibleController@loginInvisible');

// Invisible Routes
Route::group(['middleware' => ['auth:invisible','prevent-back-history']], function() {
    // Invisible Users
    Route::get('invisible/dashboard', 'InvisibleController@dashboard')->name('i_home');

    // Invisible Order
    Route::get('i_orders','Invisible\OrderController@index');
    Route::get('ajaxInvisibleOrders/{year}/{month}','Invisible\OrderController@getOrders');
    Route::get('i_addOrder' , 'Invisible\OrderController@create');
    Route::post('i_placeOrder' , 'Invisible\OrderController@placeOrderHomeDelivery');
    Route::post('i_orderItems', 'Invisible\OrderController@orderItems');
    Route::post('i_bookOrder', 'Invisible\OrderController@bookOrder');
    Route::post('i_sendOrderEmails' , 'Invisible\OrderController@sendOrderEmails');
    Route::get('i_success' , 'Invisible\OrderController@success');

    // Invisible Orders
    Route::get('i_activities/{id}','InvisibleController@user_activities');

    // Invisible Sales
    Route::get('i_sales/{id}','InvisibleController@user_sales');
    Route::get('ajaxISales/{year}/{month}/{invisible}','InvisibleController@getSales')->name('ajaxISales');

    // Invisible Refferals
    Route::get('i_refferals/{id}','InvisibleController@getReferals');

    // Invisible Promos
    Route::get('ajaxIPromos/{id}','PromoController@getIPromos')->name('ajaxIPromos');
    Route::get('i_promos' , 'PromoController@i_index');
    Route::get('i_addPromo' , 'PromoController@i_Promo');
    Route::post('i_addPromo' , 'PromoController@i_addPromo')->name('i_addPromo');
    Route::get('i_editPromo/{id}','PromoController@i_editPromo')->name('i_editPromo');
    Route::post('i_updatePromo' , 'PromoController@i_updatePromo')->name('i_updatePromo');
    Route::get('i_deletePromo/{id}','PromoController@i_deletePromo');

    Route::post('invisible-logout', 'Auth\LoginController@invisibleLogout')->name('invisible.logout');

});


Route::group(['middleware' => ['auth:web','prevent-back-history']], function() {

Route::get('/', 'HomeController@dashboard')->name('dashboard');
Route::get('/home', 'HomeController@dashboard');
Route::get('/logout', 'Auth\LoginController@logout');

Route::group(['middleware' => ['permission:all|View Invisible Users']], function() {
// Invisble Routes
Route::get('ajaxInvisibles','InvisibleController@getInvisibleUsers')->name('ajaxInvisibles');
Route::get('invisible_users' , 'InvisibleController@invisibleUsers')->name('invisible_users');
Route::get('editInvisibleUser/{id}','InvisibleController@edit')->name('editInvisible');
Route::post('editInvisible','InvisibleController@update');
Route::get('deleteInvisibleUser/{id}','InvisibleController@delete');
Route::get('invisible_sales/{id}','InvisibleController@user_sales_for_admin');
Route::get('ajaxInvisibleSales/{year}/{month}/{invisible}','InvisibleController@getSales')->name('ajaxInvisibleSales');
});

Route::group(['middleware' => ['permission:all|View Products']], function() {
// Products Routes
// Get Ajax Data for Data Tables
Route::get('ajaxProducts','ProductController@getProducts')->name('ajaxProducts');
Route::resource('products' , 'ProductController');
Route::post('updateProduct' , 'ProductController@updateProduct');
Route::get('deleteProduct/{id}','ProductController@deleteProduct');
Route::get('vat/{val}','ProductController@vat');
Route::get('sort-product','ProductController@sortProduct')->name('products.sort');
Route::post('sort-product/update','ProductController@sortProductUpdate')->name('products.sort.update');
});

Route::group(['middleware' => ['permission:all|View Combo Products']], function() {
// Combos Products
Route::get('ajaxComboProducts','ComboProductController@getComboProducts')->name('ajaxComboProducts');
Route::get('combos','ComboProductController@combos')->name('combos');
Route::get('comboEdit/{id}','ComboProductController@comboEdit');
Route::get('addCombo','ComboProductController@addCombo');
Route::post('addComboProduct','ComboProductController@addComboProduct');
Route::post('editComboProduct','ComboProductController@editComboProduct');
Route::get('getCombos/{id}','ComboProductController@getCombos');
Route::get('deleteCombo/{id}','ComboProductController@deleteCombo');

});

Route::group(['middleware' => ['permission:all|View Inventory']], function() {
// Inventory Items
Route::get('ajaxInventories/{branch}','InventoryController@getInventories');
Route::get('inventories','InventoryController@inventories')->name('inventories');
Route::get('addInventory','InventoryController@addInventory');
Route::get('editInventory/{id}','InventoryController@editInventory')->name('editInventory');
Route::post('storeInventory','InventoryController@storeInventory')->name('storeInventory');
Route::post('updateInventory','InventoryController@updateInventory')->name('updateInventory');
Route::get('deleteInventory/{id}','InventoryController@deleteInventory');

});

Route::group(['middleware' => ['permission:all|View Users']], function() {
// Users Routes
Route::get('ajaxUsers','UserController@getUsers')->name('ajaxUsers');
Route::get('users' , 'UserController@index')->name('users.index');
Route::get('addUser' , 'UserController@User');
Route::post('addUser' , 'UserController@addUser')->name('addUser');
Route::get('editUser/{id}','UserController@editUser')->name('editUser');
Route::post('updateUser' , 'UserController@updateUser')->name('updateUser');
Route::get('deleteUser/{id}','UserController@deleteUser');
// Users Logs Checking
Route::get('userLogs/{id}','UserController@userLogs')->name('userLogs');

Route::get('userPermissions/{id}','UserController@userPermissions')->name('userPermissions');
Route::post('userPermissionsSubmit','UserController@userPermissionsSubmit')->name('userPermissionsSubmit');

});


Route::group(['middleware' => ['permission:all|View Categories']], function() {
// Categories Routes
Route::get('ajaxCategories','CategoryController@getCategories')->name('ajaxCategories');
Route::get('categories' , 'CategoryController@index')->name('categories');
Route::get('addCategory' , 'CategoryController@Category');
Route::post('addCategory' , 'CategoryController@addCategory')->name('addCategory');
Route::get('editCategory/{id}','CategoryController@editCategory')->name('editCategory');
Route::post('updateCategory' , 'CategoryController@updateCategory')->name('updateCategory');
Route::get('deleteCategory/{id}','CategoryController@deleteCategory');
Route::get('categoryProducts/{id}/{product_id?}','CategoryController@categoryProducts');
Route::get('sort-category','CategoryController@sortCategory')->name('category.sort');
Route::post('sort-category/update','CategoryController@sortCategoryUpdate')->name('category.sort.update');

});


Route::group(['middleware' => ['permission:all|View Menu']], function() {
    // Categories Routes
    Route::get('ajaxMenus','MenuController@getMenus')->name('ajaxMenus');
    Route::get('menus' , 'MenuController@index')->name('menus');
    Route::get('addMenu' , 'MenuController@Menu');
    Route::post('addMenu' , 'MenuController@addMenu')->name('addMenu');
    Route::get('editMenu/{id}','MenuController@editMenu')->name('editMenu');
    Route::post('updateMenu' , 'MenuController@updateMenu')->name('updateMenu');
    Route::get('deleteMenu/{id}','MenuController@deleteMenu');
    Route::get('sort-menu','MenuController@sortMenu')->name('menu.sort');
    Route::post('sort-menu/update','MenuController@sortMenuUpdate')->name('menu.sort.update');
    
    });


Route::group(['middleware' => ['permission:all|View Sub Menu']], function() {
    // Categories Routes
    Route::get('ajaxSubMenus','SubMenuController@getSubMenus')->name('ajaxSubMenus');
    Route::get('submenus' , 'SubMenuController@index')->name('submenus');
    Route::get('addSubMenu' , 'SubMenuController@SubMenu');
    Route::post('addSubMenu' , 'SubMenuController@addSubMenu')->name('addSubMenu');
    Route::get('editSubMenu/{id}','SubMenuController@editSubMenu')->name('editSubMenu');
    Route::post('updateSubMenu' , 'SubMenuController@updateSubMenu')->name('updateSubMenu');
    Route::get('deleteSubMenu/{id}','SubMenuController@deleteSubMenu');
    Route::get('sort-sub-menu','SubMenuController@sortSubMenu')->name('sub.menu.sort');
    Route::post('sort-sub-menu/update','SubMenuController@sortSubMenuUpdate')->name('submenu.sort.update');
    
});

Route::group(['middleware' => ['permission:all|View Sub Categories']], function() {
// Sub Categories Routes
Route::get('ajaxSubCategories','SubCategoryController@getSubCategories')->name('ajaxSubCategories');
Route::get('subcategories' , 'SubCategoryController@index')->name('subcategories');
Route::get('addSubCategory' , 'SubCategoryController@Category');
Route::post('addSubCategory' , 'SubCategoryController@addSubCategory')->name('addSubCategory');
Route::get('editSubCategory/{id}','SubCategoryController@editSubCategory')->name('editSubCategory');
Route::post('updateSubCategory' , 'SubCategoryController@updateSubCategory')->name('updateSubCategory');
Route::get('deleteSubCategory/{id}','SubCategoryController@deleteSubCategory');
Route::get('sort-subcategory','SubCategoryController@sortSubCategory')->name('subcategory.sort');
Route::post('sort-subcategory/update','SubCategoryController@sortSubCategoryUpdate')->name('subcategory.sort.update');

});

Route::group(['middleware' => ['permission:all|View Areas']], function() {
// Areas Routes
Route::get('ajaxAreas','AreaController@getAreas')->name('ajaxAreas');
Route::get('areas' , 'AreaController@index')->name('areas.index');
Route::get('addArea' , 'AreaController@Area');

app/Product.php
<?php

namespace App;

use App\Category;
use App\ProductActivity;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'short_name' , 'price', 'block', 'image', 'type', 'category_id', 'for' , 'invisible_price', 'flavour', 'flavour_price', 'input_items', 'output_items', 'combo_price', 'is_for', 'details'];
    public static function block($val){
        if($val == 0)
        return "Approve";
        else
        return "Block";
    }

    public static function activity($originalValue , $modifiedValue , $attribute , $user_id , $product_id){
        ProductActivity::create([
            'original_value' => $originalValue,
            'modified_value' => $modifiedValue,
            'attribute' => $attribute,
            'user_id' => $user_id,
            'product_id' => $product_id
        ]);
    }

    public static function productName($id){
        $product = Product::where(['id' => $id])->first();
        return $product->name;
    }

    public function subcategory()
    {
        return $this->belongsTo('App\Subcategory');
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use Carbon\Carbon;
use App\VatOption;
use App\Product;
use App\Area;
use App\Branch;
use App\Subcategory;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductController extends Controller
{
    public function getProducts(){
        $category = Category::where(['name' => 'Sample'])->first();

        if($category){
            $products = Product::where(['block' => 0])   
            ->where('category_id' , '!=' , $category->id)
            ->whereIn('is_for', ['web', 'both'])
            ->orderBy('sequence')
            ->get();
        }else{
            $products = Product::where(['block' => 0])   
            ->whereIn('is_for', ['web', 'both'])
            ->orderBy('sequence')
            ->get();
        }

        $subcategories = Subcategory::where(['block' => 0])
        ->with(['products' => function($query){
            $query->where('block',0)->whereIn('is_for',['web','both']);
        }])
        ->orderBy('sequence')->get();
        
        $categories = Category::where(['block' => 0])->
        with(['products' => function($query){
            $query->where('block',0)->whereIn('is_for',['web','both']);
        }])
        ->orderBy('sequence')->get();
        $areas = Area::where(['block' => 0])->get();
        $branches = Branch::where('name' , '!=' , 'Kitchen')->get();

        foreach($categories as $category){
            $prods = [];    
            foreach($category->products as $product){
                if(!$product->subcategory_id){
                    $product->subcategory_id = 0;
                    array_push($prods , $product);
                }
            }
    
            $subcategory = new Subcategory();
            $subcategory->id = 0;
            $subcategory->name = "Other";
            $subcategory->description = "Other products";
            $subcategory->block = 0;
            $subcategory->image = '';
            $subcategory->category_id = $category->id;
            $subcategory->sequence = '';
            $subcategory->created_at = Carbon::now()->setTime(0,0)->format('Y-m-d H:i:s');
            $subcategory->updated_at = Carbon::now()->setTime(0,0)->format('Y-m-d H:i:s');
            $subcategory->products = $prods;
    
            $subcategories->push($subcategory);    

        }
        return response()->json(['status' => 200, 'products' => $products , 'subcategories' => $subcategories, 'categories' => $categories, 'areas' => $areas, 'branches' => $branches]);
    }

    public function getRegularProducts(){

        $products = Product::where(['type' => 'Regular'])
        ->where(['block' => 0])
        ->get();
        return response()->json($products, 200);
    }

    public function getProductsPOS(){

        $products = Product::where(['for' => NULL])
        ->whereIn('is_for', ['pos', 'both'])
        ->where(['block' => 0])
        ->get();

        return response()->json($products, 200);
    }

    public function vat(){
        $vat = VatOption::where(['id' => 1])->first();
        return response()->json($vat->vat_option, 200);
    }
}

resources/views/products/addProduct.blade.php
@extends('layouts.welcome')

@section('title' , 'Add Product')

@section('styles')
    <style>
      .add-product-form{
        margin:0px 20%;
      }
      .error{
        color:red;
        font-size:1rem;
      }
      .submit-btn{
        margin-top:20px; 
        margin-bottom:20px; 
      }
      #grouped_items{
        display:none;
      }
      @media screen and (max-width: 600px) {
        .add-product-form{
          margin:0px 5%;
        }
      }
      #landscape img{
        height:150px;
        width:150px;
      }
    </style>
@endsection

@section('content')
<div class="container-fluid">
<form  class="add-product-form" enctype="multipart/form-data"
 action="{{route('products.store')}}" id="add_product" method="post">
@csrf

  <!-- <div class="form-group">
      <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" class="custom-control-input" id="customRadio2" value="Regular" name="type" @if(old('type') == "Regular") checked @endif checked>
          <label class="custom-control-label" for="customRadio2">Regular</label>
      </div>

      <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" class="custom-control-input" id="customRadio1" value="Grouped" name="type" @if(old('type') == "Grouped") checked @endif>
        <label class="custom-control-label" for="customRadio1">Grouped Item</label>
      </div>

      <span class="float-right"><a href="{{url('addCategory')}}">Add Category</a></span>
  </div> -->
  <input type="hidden" name="type" value="Regular" />
  <div class="form-group">
    <label for="productInput">Product Category</label>
    <div class="form-group">
      <select class="form-control" id="category" name="category" >
        <option value="" disable> Select Category </option>
        @foreach($categories as $category)
         <option value="{{ $category->id }}"> {{ $category->name }} </option>
        @endforeach
      </select>
    </div>
    @if($errors->has('category'))
    <small id="productCategoryHelp" class="form-text error">{{ $errors->first('category') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productInput">Product Category</label>
   <div class="form-group">
      <select class="form-control" id="subcategory" name="subcategory" >
        <option value="" disable> Select SubCategory </option>
        @foreach($subcategories as $subcategory)
         <option value="{{ $subcategory->id }}"> {{ $subcategory->name }} </option>
        @endforeach
      </select>
    </div>
    @if($errors->has('subcategory'))
    <small id="productCategoryHelp" class="form-text error">{{ $errors->first('subcategory') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productInput">Product Name</label>
    <input type="text" name="name" class="form-control" id="productInput" value="{{old('name')}}" aria-describedby="productNameHelp" placeholder="Enter product name">
    @if($errors->has('name'))
    <small id="productNameHelp" class="form-text error">{{ $errors->first('name') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productShortInput">Product Short Name</label>
    <input type="text" name="short_name" class="form-control" id="productShortInput" value="{{old('short_name')}}" aria-describedby="productShortNameHelp" placeholder="Enter product short name">
    @if($errors->has('short_name'))
    <small id="productShortNameHelp" class="form-text error">{{ $errors->first('short_name') }}</small>
    @endif
  </div>


  <div class="form-group">
    <label for="productPrice">Product Price</label>
    <input type="text" name="price" class="form-control" value="{{old('price')}}" id="productPrice" aria-describedby="productPriceHelp" placeholder="Enter product price">
    @if($errors->has('price'))
    <small id="productPriceHelp" class="form-text error">{{ $errors->first('price') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productPrice">Product Invisible Price</label>
    <input type="text" name="invisible_price" class="form-control" value="{{old('invisible_price')}}" id="productPrice" aria-describedby="productPriceHelp" placeholder="Enter product invisible price">
    @if($errors->has('invisible_price'))
    <small id="productPriceHelp" class="form-text error">{{ $errors->first('invisible_price') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productPrice">Product Combo Price</label>
    <input type="text" name="combo_price" class="form-control" value="{{old('combo_price')}}" id="productPrice" aria-describedby="productPriceHelp" placeholder="Enter product combo price">
    @if($errors->has('combo_price'))
    <small id="productPriceHelp" class="form-text error">{{ $errors->first('combo_price') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productPrice">Product Details</label>
    <textarea rows="5" type="text" name="details" class="form-control"  id="productDetails" aria-describedby="productPriceHelp" placeholder="Enter Product Details">{{old('details')}}</textarea>
    @if($errors->has('details'))
    <small id="productDetails" class="form-text error">{{ $errors->first('details') }}</small>
    @endif
  </div>

  <div class="form-group">
    <label for="productInput">Product For</label>
    <div class="form-group">
      <select class="form-control" name="is_for" >
        <option value="" disable> Product For ? </option>
        <option value="web"> Web </option>
        <option value="pos"> POS </option>
        <option value="both"> Both </option>
      </select>
    </div>
    @if($errors->has('is_for'))
    <small id="productCategoryHelp" class="form-text error">{{ $errors->first('is_for') }}</small>
    @endif
  </div>

  <div class="form-group">
    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" class="custom-control-input" id="customRadio2" value="0" name="block" checked>
        <label class="custom-control-label" for="customRadio2">Approve</label>
    </div>

    <div class="custom-control custom-radio custom-control-inline">
        <input type="radio" class="custom-control-input" id="customRadio1" value="1" name="block">
        <label class="custom-control-label" for="customRadio1">Block</label>
      </div>
  </div>

  <!-- <div class="form-group">
        <input type="file" name="image[]"  multiple>
        @if($errors->has('image'))
          <small id="productImageHelp" class="form-text error">{{ $errors->first('image') }}</small>
        @endif
  </div>     -->
  <input type="hidden" id="feature_photo" name="photo" value="">


  <div class="panel panel-body">
    <div class="span4 cropme text-center" id="landscape"
      style="width: 100%; height: 285px; border: 1px dashed #ddd; background: #f1f1f1;">
      <a href="javascript:;" id="crop-image" class=" mybtn1" style="">
        <i class="icofont-upload-alt"></i> {{ __('Upload Image Here') }}
      </a>
    </div>
  </div>
  @if($errors->has('photo'))
    <small id="productImageHelp" class="form-text error">{{ $errors->first('photo') }}</small>
  @endif


<div id="grouped_items">
  <h4>Grouped Items</h4>
    <div class="row">
      <div class="col-md-2">Select</div>
      <div class="col-md-5">Item Name</div>
      <div class="col-md-5">Item Price</div>
    </div>

    <div id="grouped_items_rows"></div>
</div>

  <button id="submit" class="btn btn-primary submit-btn">Submit</button>
</form>

</div>
@endsection

<script src="/path/to/cropper.js"></script><!-- Cropper.js is required -->
<link  href="/path/to/cropper.css" rel="stylesheet">
<script src="/path/to/jquery-cropper.js"></script>

@section('scripts')
    <script>
    
  	$('.cropme').simpleCropper();
    $(document).ready(function(){
        $("input[name='type']").click(function(){
          if ($("input[name='type']:checked").val() == "Grouped") {
            loadAjax();        
          }
          else {
            // alert('One of the radio buttons is checked!');
            $('#grouped_items').css('display' , 'none');
          }
        });

        if ($("input[name='type']:checked").val() == "Grouped") {
          loadAjax();
        }
    });

    $('#category').change(function() {
      if($("input[name='type']:checked").val() == "Grouped"){
        loadAjax();
      }
    });

    function loadAjax(){
      $('#grouped_items_rows').html("");
          $.ajax({
            url: "{{url('categoryProducts')}}"+"/"+$('#category').find(":selected").val(),
            headers: {'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')},
            method: 'GET',
            success: function(data) {
              if(data.success) {
                  $('#grouped_items').css('display' , 'block');
                  var products = data.products;
                  if(products.length > 0){
                    var i = 0;
                    products.forEach(function(product) {                    
                      var html = "<div class='row'>"+
                        "<div class='col-md-2'>"+
                          "<div class='custom-control custom-checkbox'>"+
                            "<input type='checkbox' class='custom-control-input' id='customCheck"+i+"' value="+product.id+" name='items[]'>"+
                            "<label class='custom-control-label' for='customCheck"+i+"'></label>"+
                          "</div>"+
                        "</div>"+
                        "<div class='col-md-5'>"+
                              product.name+
                        "</div>"+
                        "<div class='col-md-5'>"+
                              product.price+
                        "</div>"+
                      "</div>";

                      $('#grouped_items_rows').append(html);
                      i++;
                  });
                  }else{
                    alert("No Products in this Category");
                    $('#grouped_items').css('display' , 'none');
                  }
                } 
            },
            error: function(data) {
                // If you got an error code.
            }
        }); 

    }
    </script>
@endsection

resources/views/products/sequence.blade.php
@extends('layouts.welcome')
@section('title' , 'Categories')
@section('styles')
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">

<style>
      .error{
        color:red;
        font-size:1rem;
      }
      /* #sortable1, #sortable2 {
        border: 1px solid #eee;
        width: 142px;
        min-height: 20px;
        list-style-type: none;
        margin: 0;
        padding: 5px 0 0 0;
        float: left;
        margin-right: 10px;
    }
    #sortable1 li, #sortable2 li {
        margin: 0 5px 5px 5px;
        padding: 5px;
        font-size: 1.2em;
        width: 120px;
    } */
    .box-shadow{
        border: 1px solid lightgrey; 
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        padding:20px;
        cursor:pointer;
    }
    .heading{
        padding:10px;
        font-weight:normal;
        font-size:30px;
        width:200px;
    }
    .subheading{
        padding:10px;
        font-weight:normal;
        font-size:20px;
    }
    .text{
        text-align:center;
        font-weight:bold;
        color:#0e0e0e;
        font-size:20px;
    }
</style>
@endsection

@section('content')
<div class="container-fluid">

    <div id="alert" style="display:none;" class="alert alert-success">
        Data Updated Successfully
    </div>
    
    <div id="sortable2" class="connectedSortable row">
    @foreach($categories as $category)
        @if(count($category->products) > 0)
        <hr style="color:red; width:100%;">
        <div class="col-md-12">
            <h3><span class="heading badge badge-warning badge-lg">{{ $category->name }}</span></h3>
        </div>
        <hr style="color:red; width:100%;">
                @if(count($category->products) > 0)
                    @foreach($category->products as $product)
                        @if(!$product->subcategory_id)
                        <div class="mb-3 col-md-3 box-shadow">
                            <div data-id="{{ $product->id }}" class="text">{{ $product->name }}</div>
                        </div>
                        @endif
                    @endforeach
                @endif
                @if(count($category->subcategories) > 0)
                @foreach($subcategories as $subcategory)
                    @if($subcategory->category_id == $category->id && count($subcategory->products) > 0)
                    <div class="col-md-12">
                        <h5 class="subheading badge badge-info">{{ $subcategory->name }}</h5>
                    </div>
                        @foreach($products as $product)
                            @if($product->subcategory_id == $subcategory->id)
                            <div class="mb-3 col-md-3 box-shadow">
                                <div class="row">
                                    <div class="col-md-4">
                                        <img style="width: 100px; padding-top: 20%;" src="{{ $product->image }}" alt="">
                                    </div>
                                    <div class="col-md-8 pt-5">
                                        <div data-id="{{ $product->id }}" class="text">{{ $product->name }}</div>
                                    </div>
                                </div>
                            </div>
                            @endif
                        @endforeach
                    @endif
                @endforeach
                @endif
    @endif
    @endforeach
    </div>

    <button class="btn btn-primary sorts">Update</button>
</div>
@endsection

@section('scripts')
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#sortable2" ).sortable({
      connectWith: ".connectedSortable"
    }).disableSelection();
  });

  $('.sorts').click(function(){
      var ids = [];
      var token = '{{ csrf_token() }}';
      $('.text').each(function(i, obj) {
          ids.push($(obj).data('id'));          
      });
      console.log(ids);
      $.ajax({
            url: "{{ route('products.sort.update') }}",
            type: 'POST',
            headers: {'X-CSRF-TOKEN': token},
            data:{
                ids:ids,
            },
            success: function(data) {
                if(data.status == 200) {
                    $('#alert').css('display','block');
                }
            },
            complete:function(){
                location.reload();
            } 
        }); 
  });
  </script>
@endsection